---
language: ruby
bundler_args: --without development system_tests
before_install:
  - bundle -v
  - rm Gemfile.lock || true
  - gem update --system
  - gem update bundler
  - gem --version
  - bundle -v
script: bundle exec rake test
matrix:
  fast_finish: true
  include:
  - rvm: 2.1.9
    env: PUPPET_VERSION="~> 4.0" CHECK=test
  - rvm: 2.2.6
    env: PUPPET_VERSION="~> 4.0" CHECK=test
  - rvm: 2.3.3
    env: PUPPET_VERSION="~> 4.0" CHECK=test
  - rvm: 2.4.0
    env: PUPPET_VERSION="~> 4.0" CHECK=test
  - rvm: 2.4.0
    env: PUPPET_VERSION="~> 4.0" CHECK=rubocop
  - rvm: 2.4.0
    env: PUPPET_VERSION="~> 4.0" CHECK=build DEPLOY_TO_FORGE=yes